"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import ToastProvider from "@/providers/ToastProvider";
import Header from "@/components/header";
import { useSession } from "next-auth/react";
import Auth from "./auth";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <ToastProvider />
          <Header />
          <Sidebar />
          <div className="w-full min-h-screen h-auto">
            <Auth>{children}</Auth>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
