"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import ToastProvider from "@/providers/ToastProvider";
import Header from "@/components/header";
import { useSession } from "next-auth/react";
import Auth from "./auth";
import Sidebar from "@/components/sidebar";
import "ag-grid-community/styles//ag-grid.css";
import "ag-grid-community/styles//ag-theme-quartz.css";
import useUserDeleteModal from "@/utils/hooks/user/useDeleteUserModal";
import useProfileModal from "@/utils/hooks/user/useProfileModal";
import UserProfile from "@/components/user/user-profile";
import UserEdit from "@/components/user/user-edit";
import useEditUserModal from "@/utils/hooks/user/useEditUserModal";
import ForgotPassword from "@/components/forgot-password";
import useForgotPasswordModal from "@/utils/hooks/forgotPasswordModal";
import RenewalSubscription from "@/components/renewal-subscription";
import useRenewalSubscriptionModal from "@/utils/hooks/renewalSubscriptionModal";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userDelete = useUserDeleteModal();
  const userEdit = useEditUserModal();
  const profileModal = useProfileModal();
  const forgotPasswordModal = useForgotPasswordModal();
  const renewalSubscriptionModal = useRenewalSubscriptionModal();
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <ToastProvider />
          <UserProfile
            isOpen={profileModal.isOpen}
            onClose={profileModal.onClose}
          />
          <ForgotPassword
            isOpen={forgotPasswordModal.isOpen}
            onClose={forgotPasswordModal.onClose}
          />
          <RenewalSubscription
            isOpen={renewalSubscriptionModal.isOpen}
            onClose={renewalSubscriptionModal.onClose}
          />
          <UserEdit isOpen={userEdit.isOpen} onClose={userEdit.onClose} />
          <Header />
          <div className="flex flex-row w-full">
            <Sidebar />
            <div className="w-full min-h-screen h-auto">
              <Auth>{children}</Auth>
            </div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
