"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/providers/AuthProvider";
import ToastProvider from "@/providers/ToastProvider";
import Header from "@/components/header";
import { useSession } from "next-auth/react";
import Auth from "./auth";
import Sidebar from "@/components/sidebar";
import "ag-grid-community/styles//ag-grid.css";
import "ag-grid-community/styles//ag-theme-quartz.css";
import useUserDeleteModal from "@/utils/hooks/user/useDeleteUserModal";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userDelete = useUserDeleteModal();
  console.log("tst: ", userDelete.isDelete);
  return (
    <html lang="en">
      <AuthProvider>
        <body className={inter.className}>
          <ToastProvider />
          <Header />
          <div className="flex flex-row w-full">
            <Sidebar />
            <div className="w-full min-h-screen h-auto">
              <Auth>{children}</Auth>
            </div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
